source ~/.vim/vimrcs/vimrc_from_vim_awesome.vim
source ~/.vim/vimrcs/nerdtree.vim
source ~/.vim/vimrcs/pymode.vim
source ~/.vim/vimrcs/completor.vim
source ~/.vim/vimrcs/airline.vim
source ~/.vim/vimrcs/markdown.vim
source ~/.vim/vimrcs/ctrlsf.vim
source ~/.vim/vimrcs/ibus.vim
source ~/.vim/vimrcs/custom.vim
source ~/.vim/vimrcs/nerdcommenter.vim
